serverAddr = "52.60.62.23"
serverPort = 7000
auth.method = "token"
auth.token = "gOlV6qPBAFGssA8tDJp2PdTS90weyURd8WQU3UvTFyCl"

[[proxies]]
name = "luciano_ubuntu_test"
type = "tcp"
localIP = "127.0.0.1"
localPort = 1200
remotePort = 1200
